spring.application.name=demo

# MySQL Connection Details
# Note: I used 'fileapp_db' here to match your screenshot!
spring.datasource.url=jdbc:mysql://localhost:3306/fileapp_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Properties (This creates the 'users' table automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
